version: '3'

services:
  fs_client:
    image: chfs/fs_client
    privileged: true
    depends_on:
      - meta
    network_mode: "host"
    volumes:
      - ../..:/home/stu/chfs
      - ../../build/bin/fs_client:/home/stu/fs_client

  meta:
    image: chfs/meta
    depends_on:
      - data
    ports:
      - 8080:8080
    network_mode: "host"
    volumes:
      - ../../build/bin/meta:/home/bin/meta

  data:
    image: chfs/data
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
    network_mode: "host"
    volumes:
      - ../../build/bin/data:/home/bin/data